<?php

/**
 * Routes used to figure out what the page type is and
 * serve the correct template for the <noscript>. These
 * should be identical to the routes set in Vue.js and
 * the templates should output near-enough identical content
 * as that generated by Vue.
 */

global $pageType;

$router = new Phroute\Phroute\RouteCollector();

$router->get('/post/{slug}', function () {
    return 'single';
});
$router->get('/category/{slug}', function () {
    return 'category';
});
$router->get('/archive', function () {
    return 'archive';
});
$router->get('/{slug}', function () {
    return 'page';
});
$router->get('/', function () {
    return 'index';
});

$dispatcher = new Phroute\Phroute\Dispatcher($router->getData());

$pageType = $dispatcher->dispatch(
    $_SERVER['REQUEST_METHOD'],
    parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)
);
