<?php

/**
 * Routes used to figure out what the page type is and
 * serve the correct template for the <noscript>. These
 * should be identical to the routes set in Vue.js and
 * the templates should output near-enough identical content
 * as that generated by Vue.
 */

global $route;

$router = new Phroute\Phroute\RouteCollector();

$router->get('/post/{slug}', function ($slug) {
    return [
        'pageType' => 'single',
        'slug' => $slug
    ];
});
$router->get('/category/{slug}', function ($slug) {
    return [
        'pageType' => 'category',
        'slug' => $slug
    ];
});
$router->get('/archive', function () {
    return [
        'pageType' => 'archive'
    ];
});
$router->get('/{slug}', function ($slug) {
    return [
        'pageType' => 'page',
        'slug' => $slug
    ];
});
$router->get('/', function () {
    return [
        'pageType' => 'index'
    ];
});

try {
    $dispatcher = new Phroute\Phroute\Dispatcher($router->getData());
    $route = $dispatcher->dispatch(
        $_SERVER['REQUEST_METHOD'],
        parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)
    );
} catch (Phroute\Phroute\Exception\HttpRouteNotFoundException $e) {
    $route = [];
}
